files:
  - source: '*/lang/box/en-us.all.json'
    translation: /%original_path%/%locale%.all.json
    languages_mapping:
      locale:
        fr: fr
        de: de
        pt-BR: pt-br
        es-ES: es-es
        it: it
  - source: '*/i18n/en-us.all.json'
    translation: /%original_path%/%locale%.all.json
    languages_mapping:
      locale:
        fr: fr
        de: de
        pt-BR: pt-br
        es-ES: es-es
        it: it
  - source: '*/i18n/*/en-us.all.json'
    translation: /%original_path%/%locale%.all.json
    languages_mapping:
      locale:
        fr: fr
        de: de
        pt-BR: pt-br
        es-ES: es-es
        it: it
  - source: '*/i18n/*/conf/en-us.all.json'
    translation: /%original_path%/%locale%.all.json
    languages_mapping:
      locale:
        fr: fr
        de: de
        pt-BR: pt-br
        es-ES: es-es
        it: it
