filebeat.prospectors:
- input_type: log
  json.keys_under_root: true
  paths:
      - /mnt/log/*.log
output.elasticsearch:
    hosts: ["elasticsearch:9200"]
    user: 'elastic'
    password: 'changeme'
    template.name: filebeat
    template.path: filebeat.template.json
