---
version: '3'
services:
  tracing:
    image: jaegertracing/all-in-one:latest
    environment: ['http.host=0.0.0.0', 'transport.host=127.0.0.1']
    ports:
        - "5775:5775/udp"
        - "6831:6831/udp"
        - "16686:16686"
    networks: ['tracing']

networks: {tracing: {}}
